# Generated by Django 4.1.6 on 2023-02-07 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goalcomment',
            old_name='title',
            new_name='text',
        ),
    ]
