version: '3.8'

services:
  fronted:
    image: sermalenk/skypro-front:lesson-36
    restart: always
    ports:
      - 80:80
    depends_on:
      api:
        condition: service_started
  api:
    image: pavel2232/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 8000:8000
    depends_on:
      db:
          condition: service_healthy
    container_name: todolist_app
    volumes:
      - ./TodoList_App/:/todolist/TodoList_App
      - ./core/:/todolist/core
  db:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    restart: always
    ports:
    - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 5s
      timeout: 30s
      retries: 5
    container_name: pg_db




volumes:
  TodoList_App:
  postgres_data:
  frontend: