#file: noinspection YAMLSchemaValidation
name: Build and deploy workflow
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-22.04
    env:
      DATABASE_URL: $DATABASE_URL
      SECRET_KEY: $SECRET_KEY
    steps:
      - name: clone code
        uses: actions/checkout@v3
      - name: docker build
        run: docker build -t pavel2232/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - name: docker push
        run: docker push  pavel2232/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
  deploy:
    runs-on: ubuntu-22.04
    needs: build_and_push
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
    steps:
      - name: clone code
        uses: actions/checkout@v3
      - name: render config
        run: |
          cd deploy
          cat docker-compose-ci.yml | envsubst > docker-compose.yml
      - name: copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "deploy/docker-compose.yml"
          target: "deploy"
          strip_components: 1
      - name: deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd deploy
            echo ${{ secrets.PASSWORD }} | sudo -S docker-compose down
            echo ${{ secrets.PASSWORD }} | sudo -S docker-compose up -d